[[routes]]
url = ""  # Route pour la racine (http://localhost:4242/)
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "accueil"  # Route explicite (http://localhost:4242/accueil)
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "connexion"  # Route explicite (http://localhost:4242/connexion)
controleur = "controleurs/connexion.py"
template = "connexion.html"