[[routes]]
url = ""  
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "accueil"  
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "connexion"
controleur = "controleurs/connexion.py"
template = "connexion.html"

[[routes]]
url = "parties"
controleur = "controleurs/parties.py"
template = "parties.html"

[[routes]]
url = "jeu"
controleur = "controleurs/jeu.py"
template = "jeu.html"

[[routes]]
url = "tirer"
controleur = "controleurs/tirer.py"
template = "api_reponse.html"

[[routes]]
url = "classement"
controleur = "controleurs/classement.py"
template = "classement.html"

[[routes]]
url = "deconnexion"
controleur = "controleurs/deconnexion.py"
template = "connexion.html"