[[routes]]
url = ""  
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "accueil"  
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "connexion"  # ⬅️ Le slash a été retiré ici !
controleur = "controleurs/connexion.py"
template = "connexion.html"

[[routes]]
url = "parties"  # ⬅️ Le slash a été retiré ici !
controleur = "controleurs/parties.py"
template = "parties.html"